# Welcome to Jupyter Notebook

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,33,12,54]],np.int64)

In [3]:
myarr[0]

array([ 3, 33, 12, 54], dtype=int64)

In [4]:
myarr.shape

(1, 4)

# Array Creation: Conversion from python structures

In [5]:
listarray = np.array([[1,2,3],[4,5,2]])

In [6]:
listarray

array([[1, 2, 3],
       [4, 5, 2]])

In [7]:
listarray.dtype

dtype('int32')

In [8]:
listarray.shape

(2, 3)

In [9]:
listarray.size

6

In [10]:
 np.array({32,22,3})

array({32, 3, 22}, dtype=object)

In [11]:
zeros = np.zeros((2,5))

In [12]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
zeros.shape

(2, 5)

In [14]:
rng = np.arange(15)

In [15]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
l_space = np.linspace(1,5,12)

In [17]:
l_space

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [18]:
 x = [[1,2,3],[4,5,6],[7,1,0]]

In [19]:
ar = np.array(x)

In [20]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [24]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [25]:
ar.sum(axis=0)

array([12,  8,  9])

In [26]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [27]:
ar.flat